### PR TITLE
:art: made decent ui

### LINKED ISSUE #2: Making it look decent
Style it with styles.css

### PR DESCRIPTION
**Pull request by Ankit1598**
Made the UI decent enough

Resolves #2 

image

### CODE REVIEW

**Comment by Hermes179** [comment]
Hey,@Ankit1598 I've created icons just like there is on the actual site where should PR it here ?

**Comment by Ankit1598** [comment]
@Hermes179 Well i am not sure but i guess once my PR gets merged you can make your PR so that there isn't any conflict of any kind.

**Comment by Hermes179** [comment]
Yeah sure No Problem !! Happy Hacking

**Comment by Ankit1598** [comment]
@yashpatel458 can you add the `hacktoberfest-accepted` label to the accepted PR only then it will get accepted for the event

**Pull request merged**
