### PR TITLE
UI improved

### PR DESCRIPTION
**Pull request by Harshit850**
**Here are the list of improvement done in this pull request,** 

1. Collapse button changed to _**arrow-h**_ of _font-awesome._
2. Output screen initial look changed. Default is now dark background and initial text as _**Welcome to the Live Code Editor!**_.
3. To sync the output page in current page, a medium border is added to bottom of the page.

**Here is the preview of improved UI**
image

### CODE REVIEW

**Comment by yashpatel458** [comment]
@Harshit850 There's a conflict in app.js file with a recent PR I merged. Can you look into it again?

**Comment by Harshit850** [comment]
@yashpatel458 I am new to open source, could you please elaborate more about this. Or you can share some resources which I can follow to resolve this.

**Comment by yashpatel458** [comment]
The changes you made in code is creating a conflict with the new code i added in app.js, It would break the site. So you have to clone the project again and see where your code fits in with the updated files.

**Comment by Harshit850** [comment]
@yashpatel458 understood, will fix it by the evening. Thanks for your help.

**Comment by Harshit850** [comment]
I am closing the current pull request. Will open new pull request with resolved conflicts soon.

**Comment by yashpatel458** [comment]
👍

**Pull request closed without merging**
